### ISSUE TITLE
htmlspecialchars_decode error on php7.3.1

### ISSUE THREAD

**Issue by fraserredmond** [Elephant418/Markdownify#40]
I've just upgraded to php7.3.1 (from 7.2), and am now getting this error:

> htmlspecialchars_decode() expects parameter 2 to be int, string given

I tried making a small test script to reproduce... and it doesn't happen there :-( In fact, it's intermittent in the place where it does happen.

I updated to the latest version of markdownify, and it still happens.

I suspect it's actually a php7.3 bug, but I can't reproduce it to report to them... could you add the following as a workaround, and make a new release? At `markdownify/src/Converter.php:1222` add:

```
if (gettype($quote_style) !== 'integer') {
    $quote_style = 3;
}
```

Here's the backtrace - coming from line 600 means it should be using the default value in the method:
```
- via /vendor/pixel418/markdownify/src/Converter.php:1222
- via /vendor/pixel418/markdownify/src/Converter.php:600
- via /vendor/pixel418/markdownify/src/Converter.php:331
- via /vendor/pixel418/markdownify/src/Converter.php:278
- via /vendor/pixel418/markdownify/src/ConverterExtra.php:522
```

ps. Thanks for markdownify, it's great! :-)

**Comment by tzi** [comment]
Hi!

I'm sure I can help you.
I pushed on master a little clean up. Does this help?

To test, you can set up a [VCS repository with composer](https://getcomposer.org/doc/05-repositories.md#vcs):

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/pixel418/markdownify"
        }
    ],
    "require": {
        "pixel418/markdownify": "dev-master"
    }
}
```

Cheers,
Thomas.

**Comment by fraserredmond** [comment]
Thanks that does look tidier :-) .... but it doesn't solve my problem.

I did more testing, still with no helpful results. But reading around it sounds like it's a [bug in xdebug](https://github.com/laravel/homestead/issues/1045). (It doesn't happen on our production server which doesn't have xdebug.) They've just released a new RC version yesterday with some bugfixes, so hopefully that'll solve it.

Either way, it's not your fault! :-)

**Comment by fraserredmond** [comment]
As of xdebug v2.7.0RC2 (and therefore v2.7.0 onwards) it looks like this is fixed.

**Comment by tzi** [comment]
Thanks for the heads up! :+1:
